# -*- coding: utf-8 -*-
"""Customer Data Pipeline: ETL and Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zkMRaMyUavZSDjmpPzpR7lXY1jrwhYB
"""

import pandas as pd

# -------------------
# Step 1: Extract
# -------------------
data = {
    "CustomerID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 22, 35, 28],
    "City": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Mumbai"],
    "Purchases": [5, 2, 7, 3, 4]
}

df = pd.DataFrame(data)
print("Original Data:")
print(df)

# -------------------
# Step 2: Transform
# -------------------
# Capitalize names
df['Name'] = df['Name'].str.title()

# Add TotalPurchaseValue assuming each purchase = 100 units
df['TotalPurchaseValue'] = df['Purchases'] * 100

# Basic Analytics
avg_age = df['Age'].mean()
total_revenue = df['TotalPurchaseValue'].sum()

print("\nCleaned Data:")
print(df)
print(f"\nAverage Age: {avg_age}")
print(f"Total Revenue: {total_revenue}")

# -------------------
# Step 3: Load
# -------------------
df.to_csv("cleaned_customer_data.csv", index=False)
print("\nData saved to cleaned_customer_data.csv")